apiVersion: v1
kind: Pod
metadata:
  name: target-pod
  labels:
    app: vulnerable-app
spec:
  containers:
  - name: lab-app
    image: placeholder
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m